import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { GeistSans, GeistMono } from "geist/font";
import "./globals.css";
// import AuthProvider from "@/components/AuthProvider";
import AuthProvider from "@/components/AuthProvider";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
// const geistSans = GeistSans;
// const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
